default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  username: root
  password: <%=ENV['DB_PASS']%>
  database: colorado_lotter_dev

production:
  <<: *default
  database: colorado_lottery
  host: <%=ENV['DB_HOST']%>
  username: <%=ENV['DB_USER']%>
  password: <%=ENV['DB_PASS']%>